export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
  },
  dashboard: {
    summary: '/dashboard/summary',
    pendingRequests: '/dashboard/pending-requests',
  },
  personnel: {
    agents: '/personnel/agents',
    agentDuplicateIndex: '/personnel/agents/duplicate-index',
    agentDuplicateCases: '/personnel/agents/duplicate-cases',
    agentMerge: '/personnel/agents/merge',
    agentMatriculeSuggestion: '/personnel/agents/matricule-suggestion',
    agentMatriculeSuggestionAudit: '/personnel/agents/matricule-suggestion-audit',
    agentDetail: (id: string) => `/personnel/agents/${id}`,
    agentAuditTrail: (id: string) => `/personnel/agents/${id}/audit-trail`,
    upload: '/personnel/uploads',
    dossiers: '/personnel/dossiers',
    affectations: '/personnel/affectations',
  },
  leave: {
    requests: '/leave/requests',
    balances: '/leave/balances',
    events: '/leave/events',
  },
  organization: {
    units: '/organization/units',
    unit: (id: string) => `/organization/units/${encodeURIComponent(id)}`,
    budgetedPositions: '/organization/positions/budgeted',
    vacantPositions: '/organization/positions/vacant',
  },
  recruitment: {
    applications: '/recruitment/applications',
    applicationDuplicates: '/recruitment/applications/duplicates',
    applicationDuplicateLinks: '/recruitment/applications/duplicates/links',
    applicationDuplicateLinkAction: '/recruitment/applications/duplicates/link',
    applicationStatus: (reference: string) => `/recruitment/applications/${encodeURIComponent(reference)}/status`,
    applicationComments: (reference: string) => `/recruitment/applications/${encodeURIComponent(reference)}/comments`,
    applicationScores: '/recruitment/application-scores',
    scoringPolicy: '/recruitment/scoring-policy',
    shortlistSuggest: '/recruitment/shortlists/suggest',
    shortlistValidations: '/recruitment/shortlists/validations',
    shortlistValidate: (reference: string) => `/recruitment/shortlists/${encodeURIComponent(reference)}/validate`,
    interviewQuestionBank: '/recruitment/interview-question-bank',
    interviewQuestionBankImport: '/recruitment/interview-question-bank/import',
    interviewQuestionBankExport: '/recruitment/interview-question-bank/export',
    interviews: '/recruitment/interviews',
    interviewReschedule: (id: string) => `/recruitment/interviews/${encodeURIComponent(id)}/reschedule`,
    interviewEvaluations: (id: string) => `/recruitment/interviews/${encodeURIComponent(id)}/evaluations`,
    campaignWorkloadForecast: '/recruitment/campaigns/workload-forecast',
    campaignBudgets: '/recruitment/campaigns/budgets',
    onboarding306090: '/recruitment/onboarding/306090',
    onboarding306090Feedback: (reference: string) =>
      `/recruitment/onboarding/${encodeURIComponent(reference)}/306090-feedback`,
    onboardingSuccessScores: '/recruitment/onboarding/success-scores',
    onboardingSyncLogs: '/recruitment/onboarding/sync-logs',
    onboardingSync: (reference: string) => `/recruitment/onboarding/${encodeURIComponent(reference)}/sync`,
    ruleEngineRules: '/recruitment/rules',
    ruleEngineSimulate: '/recruitment/rules/simulate',
    ruleEngineExecutions: '/recruitment/rules/executions',
    controlTower: '/recruitment/control-tower',
    executiveDashboard: '/recruitment/executive-dashboard',
    executiveDashboardExport: '/recruitment/executive-dashboard/export',
    biExport: '/recruitment/bi-export',
    biExportLogs: '/recruitment/bi-export/logs',
    observability: '/recruitment/observability',
    observabilityEvents: '/recruitment/observability/events',
    uploads: '/recruitment/uploads',
    campaigns: '/recruitment/campaigns',
    onboarding: '/recruitment/onboarding',
    notifications: '/recruitment/notifications',
    auditLogs: '/recruitment/audit-logs',
  },
  careers: {
    moves: '/careers/movements',
  },
  performance: {
    campaigns: '/performance/campaigns',
    results: '/performance/results',
  },
  training: {
    sessions: '/training/sessions',
    catalog: '/training/catalog',
    requests: '/training/requests',
    requestDecision: (reference: string) =>
      `/training/requests/${encodeURIComponent(reference)}/decision`,
  },
  discipline: {
    cases: '/discipline/cases',
  },
  documents: {
    library: '/documents/library',
    item: (reference: string) => `/documents/library/${encodeURIComponent(reference)}`,
    sign: (reference: string) => `/documents/library/${encodeURIComponent(reference)}/sign`,
    assign: (reference: string) => `/documents/library/${encodeURIComponent(reference)}/assign`,
    requests: '/documents/requests',
    requestDecision: (reference: string) =>
      `/documents/requests/${encodeURIComponent(reference)}/decision`,
    audit: '/documents/audit-logs',
    analytics: '/documents/analytics',
    overdue: '/documents/overdue',
    archiveRun: '/documents/archive-run',
    purgeArchives: '/documents/purge-archives',
    inbox: '/documents/inbox',
    inboxRead: (reference: string) => `/documents/inbox/${encodeURIComponent(reference)}/read`,
    inboxAcknowledge: (reference: string) => `/documents/inbox/${encodeURIComponent(reference)}/acknowledge`,
  },
  notifications: {
    inbox: '/notifications/inbox',
    read: (id: string) => `/notifications/inbox/${encodeURIComponent(id)}/read`,
    jobs: '/notifications/delivery-jobs',
    process: '/notifications/process',
  },
  workflows: {
    definitions: '/workflows/definitions',
    instances: '/workflows/instances',
    instanceAction: (id: string) => `/workflows/instances/${id}/actions`,
    automationStatus: '/workflows/automation/status',
    automationChannels: '/workflows/automation/channels',
    automationPolicy: '/workflows/automation/policy',
    automationSimulate: '/workflows/automation/simulate',
    automationRunCycle: '/workflows/automation/run-cycle',
    automationEvents: '/workflows/automation/events',
    automationEventsClear: '/workflows/automation/events/clear',
  },
  admin: {
    users: '/admin/users',
    roles: '/admin/roles',
    audit: '/admin/audit-logs',
  },
};
